# config/packages/api_platform.yaml

api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    patch_formats:
        json: ['application/merge-patch+json']
    collection:
        pagination:
            enabled: true
            enabled_parameter_name: 'pagination_enabled'
            items_per_page_parameter_name: 'items_per_page'
            page_parameter_name: 'page'
            partial_parameter_name: 'partial'
    graphql:
        enabled: true




